name: Publish CI

on:
  push:
    tags:
        - '*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Build
      run: make build publish DOCKER_TAG=$GIT_TAG_NAME
